# 01 Data Cleaning and Validation

## Tata Motors Financial Performance & Business Health Analysis

In this notebook, I validate the cleaned financial datasets that I created from Tata Motors' consolidated annual reports.

My main goal in this step is to make sure that the income statement, balance sheet, cash flow statement, and financial ratios datasets are ready for analysis. I also standardize the financial year labels so that the final merged dataset has one clean row for each year from FY2021 to FY2025.

In [1]:
# I import the libraries required for loading, cleaning, validation, and file handling.
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

## 1. Define project paths

In this step, I define the main project folders. The path logic works whether I run this notebook from the project root folder or from inside the `notebooks` folder.

In [2]:
# I detect the project root automatically.
current_path = Path.cwd()

if current_path.name.lower() == "notebooks":
    PROJECT_ROOT = current_path.parent
else:
    PROJECT_ROOT = current_path

DATA_CLEANED = PROJECT_ROOT / "data" / "cleaned"
REPORTS_DIR = PROJECT_ROOT / "reports"

REPORTS_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Cleaned data folder:", DATA_CLEANED)
print("Reports folder:", REPORTS_DIR)

Project root: d:\Github Project\Tata Motors Financial Analysis
Cleaned data folder: d:\Github Project\Tata Motors Financial Analysis\data\cleaned
Reports folder: d:\Github Project\Tata Motors Financial Analysis\reports

## 2. Load cleaned datasets

Here, I load the four cleaned datasets that form the base of this project.

In [3]:
# I define the file paths for the cleaned financial datasets.
income_path = DATA_CLEANED / "income_statement_combined_FY2021_to_FY2025.csv"
balance_path = DATA_CLEANED / "balance_sheet_combined_FY2021_to_FY2025.csv"
cashflow_path = DATA_CLEANED / "cash_flow_statement_combined_FY2021_to_FY2025.csv"
ratios_path = DATA_CLEANED / "financial_ratios.csv"

required_files = [income_path, balance_path, cashflow_path, ratios_path]

for file_path in required_files:
    if not file_path.exists():
        raise FileNotFoundError(f"Required file not found: {file_path}")

income_df = pd.read_csv(income_path)
balance_df = pd.read_csv(balance_path)
cashflow_df = pd.read_csv(cashflow_path)
ratios_df = pd.read_csv(ratios_path)

print("Income statement shape:", income_df.shape)
print("Balance sheet shape:", balance_df.shape)
print("Cash flow statement shape:", cashflow_df.shape)
print("Financial ratios shape:", ratios_df.shape)

Income statement shape: (5, 35)
Balance sheet shape: (5, 58)
Cash flow statement shape: (5, 31)
Financial ratios shape: (5, 35)

## 3. Preview datasets

I preview the first few rows of each dataset to confirm that the files have loaded correctly.

In [4]:
display(income_df.head())
display(balance_df.head())
display(cashflow_df.head())
display(ratios_df.head())

,financial_year,source_report,unit,revenue,other_operating_revenues,total_revenue_from_operations,other_income,total_income,cost_of_materials_consumed,basis_adjustment_on_hedge_accounted_derivatives,purchase_of_products_for_sale,changes_in_inventories,employee_benefits_expense,finance_costs,ccp_share_fair_value_gain_loss,foreign_exchange_gain_loss_net,depreciation_and_amortisation_expense,product_development_engineering_expenses,other_expenses,amount_transferred_to_capital_and_other_account,total_expenses,profit_before_share_exceptional_items_and_tax,share_of_profit_loss_equity_accounted_investees,profit_before_exceptional_items_and_tax,exceptional_items_loss_net,profit_before_tax,current_tax,deferred_tax,total_tax_expense_credit,profit_from_continuing_operations,profit_loss_from_discontinued_operations,profit_for_year,profit_attributable_to_shareholders,profit_attributable_to_non_controlling_interests,notes
0,FY2021,tata-motor-IAR-2020-21.pdf,₹ crore,246972.17,2822.58,249794.75,2643.19,252437.94,141357.27,-35.16,12250.09,4684.16,27648.48,8097.17,NaN,-1732.15,23546.71,5226.63,40921.97,-12849.13,249151.20,NaN,-378.96,3286.74,13761.02,-10474.28,1710.18,831.68,2541.86,-13016.14,NaN,-13395.10,-13451.39,56.29,FY21 statement presents share of joint venture...
1,FY2022,tata-motor-IAR-2021-22.pdf,₹ crore,275235.23,3218.39,278453.62,3053.63,281507.25,160920.56,1322.50,18374.77,1590.49,30808.52,9311.86,14.45,78.68,24835.69,9209.50,47133.85,-14397.29,287881.08,NaN,-74.06,-6373.83,629.58,-7003.41,2669.98,1561.31,4231.29,-11234.70,NaN,-11308.76,-11441.47,132.71,FY22 statement presents share of joint venture...
2,FY2023,tata-motor-IAR-2022-23.pdf,₹ crore,342874.59,3092.38,345966.97,4633.18,350600.15,208944.31,726.26,22306.95,-4781.62,33654.70,10225.48,13.75,-103.88,24860.36,10661.96,61785.96,-18434.84,349133.13,NaN,336.38,1467.02,-1590.53,3057.55,3258.35,-2554.29,704.06,2353.49,NaN,2689.87,2414.29,275.58,FY23 statement presents share of joint venture...
3,FY2024,tata-motor-IAR-2023-24.pdf,₹ crore,434984.12,2943.65,437927.77,5949.92,443877.69,249277.79,NaN,25043.44,-1565.53,42486.64,9985.76,47.90,23.84,27270.13,10958.72,78874.98,-26758.35,415645.32,28232.37,699.80,28932.17,977.06,27955.11,4937.13,-8788.77,-3851.64,NaN,NaN,31806.75,31399.09,407.66,FY24 statement includes share of profit in equ...
4,FY2025,tata-motor-IAR-2024-25.pdf,₹ crore,436821.00,2874.00,439695.00,6244.00,445939.00,241148.00,NaN,27802.00,2836.00,47767.00,5083.00,-84.00,-922.00,23256.00,10716.00,85399.00,-31105.00,411896.00,34043.00,287.00,34330.00,550.00,33780.00,5023.00,5479.00,10502.00,23278.00,4871.0,28149.00,27830.00,319.00,FY25 values are rounded to whole crores as pre...

,financial_year,fiscal_year_end,source_report,unit,property_plant_and_equipment,capital_work_in_progress,right_of_use_assets,goodwill,other_intangible_assets,intangible_assets_under_development,investment_in_equity_accounted_investees,non_current_investments,non_current_finance_receivables,non_current_loans,non_current_other_financial_assets,deferred_tax_assets_net,non_current_tax_assets_net,other_non_current_assets,total_non_current_assets,inventories,current_investments,trade_receivables,cash_and_cash_equivalents,bank_balances_other_than_cash,current_finance_receivables,current_loans,current_other_financial_assets,current_tax_assets_net,other_current_assets,total_current_assets_excluding_held_for_sale,assets_classified_as_held_for_sale,total_assets,equity_share_capital,other_equity,equity_attributable_to_owners,non_controlling_interests,total_equity,non_current_borrowings,non_current_lease_liabilities,ccps_liability_portion,non_current_other_financial_liabilities,non_current_provisions,deferred_tax_liabilities_net,other_non_current_liabilities,total_non_current_liabilities,current_borrowings,current_lease_liabilities,trade_payables_micro_small_enterprises,trade_payables_others,acceptances,current_other_financial_liabilities,other_current_liabilities,current_provisions,current_tax_liabilities_net,liabilities_associated_with_assets_held_for_sale,total_current_liabilities,total_equity_and_liabilities,notes
0,FY2020-21,2021-03-31,76th Integrated Annual Report 2020-21,INR crore,79640.05,8377.14,6490.66,803.72,51773.18,12586.79,4200.79,1368.30,16846.82,1204.59,5813.98,4520.35,1003.30,1608.49,196238.16,36088.59,19051.19,12679.08,31700.01,15092.45,17868.09,1749.40,5274.32,865.31,6298.40,146666.84,220.80,343125.80,765.81,54480.91,55246.72,1573.49,56820.21,93112.77,5412.06,NaN,2556.35,13606.76,1555.89,12312.58,128556.41,21662.79,814.00,186.21,67993.63,7860.31,34854.59,10443.18,12848.03,1086.44,0.00,157749.18,343125.80,Consolidated balance sheet; total_current_asse...
1,FY2021-22,2022-03-31,77th Integrated Annual Report 2021-22,INR crore,80900.13,3529.04,6686.02,807.17,50462.13,6722.05,4349.39,2320.92,11135.85,843.35,5179.49,3870.85,1196.79,5639.21,183642.39,35240.34,22709.22,12442.12,38159.01,2510.18,22095.35,1671.93,3799.82,259.84,7565.88,146453.69,523.85,330619.93,765.88,43795.36,44561.24,4271.06,48832.30,97759.17,5962.44,NaN,5333.66,12955.89,1558.44,7535.22,131104.82,41917.87,809.55,183.92,59786.46,9779.95,14420.24,11761.54,10766.31,1253.85,3.12,150682.81,330619.93,Consolidated balance sheet; assets held-for-sa...
2,FY2022-23,2023-03-31,78th Integrated Annual Report 2022-23 / 79th I...,INR crore,76641.43,5219.87,7801.04,840.60,46796.69,9054.63,4675.66,2865.19,7416.41,745.31,7153.00,5184.67,1556.36,8602.05,184552.91,40755.39,18838.31,15737.97,31886.95,5128.61,23417.31,123.53,4966.03,259.26,9587.33,150700.69,827.78,336081.38,766.02,44555.77,45321.79,7277.72,52599.51,88695.81,7568.49,2500.0,5822.47,13196.53,1406.95,9264.29,128454.54,36964.66,884.48,316.01,71739.76,7195.99,13828.58,11033.00,11810.66,1254.19,0.00,155027.33,336081.38,Consolidated balance sheet; FY23 values kept i...
3,FY2023-24,2024-03-31,79th Integrated Annual Report 2023-24,INR crore,73124.66,10937.33,8059.49,860.26,39241.05,24761.10,5340.28,3377.55,6094.66,441.58,9084.66,13099.02,2129.73,5720.44,202271.81,47788.29,14253.24,16951.81,40014.76,5791.93,24069.50,196.70,8121.47,101.15,10429.39,167718.24,673.91,370663.96,766.50,84151.52,84918.02,8175.91,93093.93,62148.53,7669.52,2547.9,1673.12,16536.66,1143.35,12233.95,103953.03,36351.56,1092.89,502.31,87540.64,5935.57,15385.12,12990.30,12291.47,1527.14,0.00,173617.00,370663.96,Consolidated balance sheet.
4,FY2024-25,2025-03-31,80th Integrated Annual Report 2024-25,INR crore,72536.00,17624.00,8476.00,895.00,33790.00,48182.00,5534.00,2923.00,0.00,99.00,12185.00,7176.00,2045.00,6852.00,218317.00,47269.00,27199.00,13248.00,34349.00,6485.00,0.00,72.00,18984.00,411.00,11794.00,159811.00,514.00,378642.00,736.00,115408.00,116144.00,6610.00,122754.00,40217.00,7642.00,2464.0,901.00,20935.00,1669.00,15376.00,89204.00,22282.00,1399.00,452.00,93626.00,3290.00,14318.00,13340.00,15831.00,2146.00,0.00,166684.00,378642.00,Consolidated balance sheet; FY25 report presen...

,financial_year,year_end,profit_for_year,depreciation_and_amortisation,cash_flow_before_working_capital_changes,cash_generated_from_operations,income_tax_paid,net_cash_from_operating_activities,payments_for_property_plant_equipment,payments_for_intangible_assets,total_capex_payments,proceeds_from_sale_of_property_plant_equipment,interest_received,dividend_received,net_cash_used_in_investing_activities,proceeds_from_long_term_borrowings,repayment_of_long_term_borrowings,proceeds_from_short_term_borrowings,repayment_of_short_term_borrowings,interest_paid,dividend_paid,net_cash_from_financing_activities,net_increase_decrease_cash_equivalents,opening_cash_and_cash_equivalents,cash_reclassified_or_disposed,effect_of_fx_on_cash,closing_cash_and_cash_equivalents,auto_free_cash_flow,source_report,unit,notes
0,FY2020_21,2021-03-31,-13395.10,23546.71,31197.64,31105.07,-2104.56,29000.51,-11775.65,-8429.75,-20205.40,350.58,427.51,18.37,-26126.25,29642.36,-18629.61,20807.15,-11078.93,-8122.94,-1.56,9904.20,12778.46,18467.80,0.0,453.75,31700.01,5317.0,tata-motor-IAR-2021-22.pdf / tata-motor-IAR-20...,INR crore,FY21 cash-flow figures taken from consolidated...
1,FY2021_22,2022-03-31,-11308.76,24835.69,26942.77,16192.47,-1909.64,14282.83,-9039.40,-6129.02,-15168.42,230.10,652.94,32.01,-4775.12,31308.62,-23355.80,16866.24,-19460.45,-9251.42,-1.53,-3380.17,6127.54,31700.01,0.0,331.46,38159.01,-9254.0,tata-motor-IAR-2022-23.pdf / tata-motor-IAR-20...,INR crore,FY22 values use latest comparative where avail...
2,FY2022_23,2023-03-31,2689.87,24860.36,41694.13,38567.00,-3178.99,35388.01,-8492.63,-9603.05,-18095.68,285.03,973.44,46.42,-16804.16,16315.06,-31559.46,28125.45,-30997.82,-9335.96,0.00,-26242.90,-7659.05,38159.01,0.0,1386.99,31886.95,7840.0,tata-motor-IAR-2023-24.pdf / tata-motor-IAR-20...,INR crore,FY23 values taken from consolidated cash-flow ...
3,FY2023_24,2024-03-31,31806.75,27270.13,65106.46,72431.63,-4516.27,67915.36,-12974.74,-18438.89,-31413.63,231.09,2492.74,46.70,-22828.09,11629.40,-31675.20,10194.10,-15656.51,-9332.32,-769.27,-37005.99,8081.28,31886.95,0.0,46.53,40014.76,26924.0,tata-motor-IAR-2024-25.pdf / tata-motor-IAR-20...,INR crore,FY24 cash-flow values include latest re-presen...
4,FY2024_25,2025-03-31,28149.00,23256.00,58937.00,67093.00,-3991.00,63102.00,-15189.00,-22853.00,-38042.00,974.00,2420.00,64.00,-47594.00,7386.00,-19600.00,846.00,-1843.00,-5814.00,-2303.00,-18786.00,-3278.00,40015.00,-3231.0,843.00,34349.00,22348.0,tata-motor-IAR-2024-25.pdf,INR crore,FY25 consolidated cash-flow statement; cash_re...

,financial_year,revenue_from_operations_cr,total_income_cr,profit_before_tax_cr,profit_after_tax_cr,total_assets_cr,total_equity_cr,total_liabilities_cr,current_assets_cr,current_liabilities_cr,cash_and_cash_equivalents_cr,current_investments_cr,total_borrowings_cr,net_cash_from_operating_activities_cr,auto_free_cash_flow_cr,capex_payments_cr,net_profit_margin_pct,pbt_margin_pct,expense_to_income_ratio_pct,return_on_assets_pct,return_on_equity_pct,asset_turnover_ratio,current_ratio,quick_ratio,cash_ratio,working_capital_cr,debt_to_equity_ratio,debt_ratio,operating_cash_flow_margin_pct,free_cash_flow_margin_pct,capex_to_revenue_pct,source_income_statement,source_balance_sheet,source_cash_flow,notes
0,FY2020-21,249794.75,252437.94,-10474.28,-13395.10,343125.80,56820.21,286305.59,146887.64,157749.18,31700.01,19051.19,114775.56,29000.51,5317.0,-20205.40,-5.36,-4.19,98.70,-3.90,-23.57,0.728,0.93,0.70,0.32,-10861.54,2.02,0.83,11.61,2.13,8.09,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...
1,FY2021-22,278453.62,281507.25,-7003.41,-11308.76,330619.93,48832.30,281787.63,146977.54,150682.81,38159.01,22709.22,139677.04,14282.83,-9254.0,-15168.42,-4.06,-2.52,102.26,-3.36,-21.41,0.827,0.98,0.74,0.40,-3705.27,2.86,0.85,5.13,-3.32,5.45,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...
2,FY2022-23,345966.97,350600.15,3057.55,2689.87,336081.38,52599.51,283481.87,151528.47,155027.33,31886.95,18838.31,125660.47,35388.01,7840.0,-18095.68,0.78,0.88,99.58,0.81,5.30,1.038,0.98,0.71,0.33,-3498.86,2.39,0.84,10.23,2.27,5.23,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...
3,FY2023-24,437927.77,443877.69,27955.11,31806.75,370663.96,93093.93,277570.03,168392.15,173617.00,40014.76,14253.24,98500.09,67915.36,26924.0,-31413.63,7.26,6.38,93.64,9.00,43.66,1.239,0.97,0.69,0.31,-5224.85,1.06,0.75,15.51,6.15,7.17,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...
4,FY2024-25,439695.00,445939.00,33780.00,28149.00,378642.00,122754.00,255888.00,160325.00,166684.00,34349.00,27199.00,62499.00,63102.00,22348.0,-38042.00,6.40,7.68,92.37,7.51,26.08,1.174,0.96,0.68,0.37,-6359.00,0.51,0.68,14.35,5.08,8.65,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...

## 4. Standardize financial year labels

I noticed that the same financial year can appear in different formats across files, such as `FY2020-21`, `FY2020_21`, `FY2021`, or `FY2024_represented`.

In this step, I convert all financial year labels into one consistent format: `FY2021`, `FY2022`, `FY2023`, `FY2024`, and `FY2025`.

In [6]:
def standardize_financial_year(value):
    """I convert different financial year label formats into a single clean format."""
    if pd.isna(value):
        return value

    value = str(value).strip()

    year_mapping = {
        "FY2020-21": "FY2021",
        "FY2020_21": "FY2021",
        "FY2020/21": "FY2021",
        "FY21": "FY2021",
        "FY2021": "FY2021",

        "FY2021-22": "FY2022",
        "FY2021_22": "FY2022",
        "FY2021/22": "FY2022",
        "FY22": "FY2022",
        "FY2022": "FY2022",

        "FY2022-23": "FY2023",
        "FY2022_23": "FY2023",
        "FY2022/23": "FY2023",
        "FY23": "FY2023",
        "FY2023": "FY2023",

        "FY2023-24": "FY2024",
        "FY2023_24": "FY2024",
        "FY2023/24": "FY2024",
        "FY24": "FY2024",
        "FY2024": "FY2024",
        "FY2024_represented": "FY2024",
        "FY2024_re-presented": "FY2024",
        "FY2024 represented": "FY2024",

        "FY2024-25": "FY2025",
        "FY2024_25": "FY2025",
        "FY2024/25": "FY2025",
        "FY25": "FY2025",
        "FY2025": "FY2025",
    }

    return year_mapping.get(value, value)

# I keep the original year column for checking and then standardize the working financial_year column.
datasets = {
    "income_statement": income_df.copy(),
    "balance_sheet": balance_df.copy(),
    "cash_flow_statement": cashflow_df.copy(),
    "financial_ratios": ratios_df.copy(),
}

for name, df in datasets.items():
    if "financial_year" not in df.columns:
        raise KeyError(f"financial_year column is missing in {name}")

    df["financial_year_original"] = df["financial_year"]
    df["financial_year"] = df["financial_year"].apply(standardize_financial_year)
    datasets[name] = df

# I display the original and standardized year values for each dataset.
for name, df in datasets.items():
    print(f"{name} year labels:")
    display(df[["financial_year_original", "financial_year"]].drop_duplicates().sort_values("financial_year"))

income_statement year labels:

  financial_year_original financial_year
0                  FY2021         FY2021
1                  FY2022         FY2022
2                  FY2023         FY2023
3                  FY2024         FY2024
4                  FY2025         FY2025

balance_sheet year labels:

  financial_year_original financial_year
0               FY2020-21         FY2021
1               FY2021-22         FY2022
2               FY2022-23         FY2023
3               FY2023-24         FY2024
4               FY2024-25         FY2025

cash_flow_statement year labels:

  financial_year_original financial_year
0               FY2020_21         FY2021
1               FY2021_22         FY2022
2               FY2022_23         FY2023
3               FY2023_24         FY2024
4               FY2024_25         FY2025

financial_ratios year labels:

  financial_year_original financial_year
0               FY2020-21         FY2021
1               FY2021-22         FY2022
2               FY2022-23         FY2023
3               FY2023-24         FY2024
4               FY2024-25         FY2025

## 5. Remove duplicate year rows after standardization

After standardizing years, I make sure each dataset has only one row per financial year. If a duplicate exists, I keep the last available record because the later extracted/represented version is usually the cleaner one.

In [7]:
expected_years = ["FY2021", "FY2022", "FY2023", "FY2024", "FY2025"]

cleaned_datasets = {}

for name, df in datasets.items():
    before_rows = len(df)

    # I keep only the five-year analysis window for this project.
    df = df[df["financial_year"].isin(expected_years)].copy()

    # I sort by the standardized financial year and remove duplicate years if any exist.
    df["financial_year"] = pd.Categorical(df["financial_year"], categories=expected_years, ordered=True)
    df = df.sort_values("financial_year").drop_duplicates(subset=["financial_year"], keep="last")
    df["financial_year"] = df["financial_year"].astype(str)

    after_rows = len(df)
    cleaned_datasets[name] = df

    print(f"{name}: {before_rows} rows before cleaning, {after_rows} rows after cleaning")
    print("Final years:", df["financial_year"].tolist())

income_clean = cleaned_datasets["income_statement"]
balance_clean = cleaned_datasets["balance_sheet"]
cashflow_clean = cleaned_datasets["cash_flow_statement"]
ratios_clean = cleaned_datasets["financial_ratios"]

income_statement: 5 rows before cleaning, 5 rows after cleaning
Final years: ['FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025']
balance_sheet: 5 rows before cleaning, 5 rows after cleaning
Final years: ['FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025']
cash_flow_statement: 5 rows before cleaning, 5 rows after cleaning
Final years: ['FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025']
financial_ratios: 5 rows before cleaning, 5 rows after cleaning
Final years: ['FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025']

## 6. Check expected financial years

I check whether all datasets contain the same five-year period before I merge them.

In [8]:
expected_years_set = set(expected_years)
validation_messages = []

for name, df in cleaned_datasets.items():
    available_years = set(df["financial_year"])
    missing_years = sorted(expected_years_set - available_years)
    extra_years = sorted(available_years - expected_years_set)

    if not missing_years and not extra_years and len(df) == 5:
        status = "PASS"
    else:
        status = "FAIL"

    validation_messages.append({
        "dataset": name,
        "check_name": "expected_financial_years",
        "status": status,
        "details": f"missing={missing_years}; extra={extra_years}; rows={len(df)}"
    })

    print(f"{name}: {status}")
    print(f"  Missing years: {missing_years}")
    print(f"  Extra years: {extra_years}")
    print(f"  Row count: {len(df)}")

income_statement: PASS
  Missing years: []
  Extra years: []
  Row count: 5
balance_sheet: PASS
  Missing years: []
  Extra years: []
  Row count: 5
cash_flow_statement: PASS
  Missing years: []
  Extra years: []
  Row count: 5
financial_ratios: PASS
  Missing years: []
  Extra years: []
  Row count: 5

## 7. Clean numeric columns

I convert financial columns into numeric format wherever possible. I keep descriptive columns such as source report, unit, and notes as text.

In [9]:
def clean_numeric_columns(df, exclude_cols=("financial_year", "financial_year_original", "source_report", "unit", "notes")):
    """I clean numeric-looking columns while keeping descriptive columns unchanged."""
    cleaned_df = df.copy()

    for col in cleaned_df.columns:
        if col in exclude_cols:
            continue

        if cleaned_df[col].dtype == "object":
            cleaned_series = (
                cleaned_df[col]
                .astype(str)
                .str.replace(",", "", regex=False)
                .str.replace("₹", "", regex=False)
                .str.replace("INR", "", regex=False)
                .str.replace("crore", "", regex=False)
                .str.replace("%", "", regex=False)
                .str.strip()
            )

            # I convert bracketed negatives like (123.45) into -123.45.
            cleaned_series = cleaned_series.str.replace(r"^\((.*)\)$", r"-", regex=True)
            cleaned_df[col] = pd.to_numeric(cleaned_series, errors="ignore")

    return cleaned_df

income_clean = clean_numeric_columns(income_clean)
balance_clean = clean_numeric_columns(balance_clean)
cashflow_clean = clean_numeric_columns(cashflow_clean)
ratios_clean = clean_numeric_columns(ratios_clean)

print("Numeric cleaning completed.")

Numeric cleaning completed.

C:\Users\vatsa\AppData\Local\Temp\ipykernel_7752\3714517769.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  cleaned_df[col] = pd.to_numeric(cleaned_series, errors="ignore")
C:\Users\vatsa\AppData\Local\Temp\ipykernel_7752\3714517769.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  cleaned_df[col] = pd.to_numeric(cleaned_series, errors="ignore")
C:\Users\vatsa\AppData\Local\Temp\ipykernel_7752\3714517769.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  cleaned_df[col] = pd.to_numeric(cleaned_series, errors="ignore")
C:\Users\vatsa\AppData\Local\Temp\ipykernel_7752\3714517769.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  cleaned_df[col] = pd.to_numeric(cleaned_series, errors="ignore")
C:\Users\vatsa\AppData\Local\Temp\ipykernel_7752\3714517769.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  cleaned_df[col] = pd.to_numeric(cleaned_series, errors="ignore")

## 8. Check missing values

I check missing values after cleaning. Some missing values are acceptable because not every annual report uses exactly the same presentation format, but I still need to know where the gaps are.

In [11]:
for name, df in {
    "income_statement": income_clean,
    "balance_sheet": balance_clean,
    "cash_flow_statement": cashflow_clean,
    "financial_ratios": ratios_clean,
}.items():
    print(f"Missing values in {name}:")
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    if missing.empty:
        print("No missing values found.")
    else:
        display(missing.to_frame("missing_count"))

Missing values in income_statement:

                                                 missing_count
profit_loss_from_discontinued_operations                     4
profit_before_share_exceptional_items_and_tax                3
basis_adjustment_on_hedge_accounted_derivatives              2
ccp_share_fair_value_gain_loss                               1
profit_from_continuing_operations                            1

Missing values in balance_sheet:

                        missing_count
ccps_liability_portion              2

Missing values in cash_flow_statement:
No missing values found.
Missing values in financial_ratios:
No missing values found.

## 9. Check data types

I review the data types so that I can confirm which columns are numeric and which columns are descriptive.

In [13]:
for name, df in {
    "income_statement": income_clean,
    "balance_sheet": balance_clean,
    "cash_flow_statement": cashflow_clean,
    "financial_ratios": ratios_clean,
}.items():
    print(f"Data types for {name}:")
    display(df.dtypes.to_frame("dtype"))

Data types for income_statement:

                                                    dtype
financial_year                                     object
source_report                                      object
unit                                               object
revenue                                           float64
other_operating_revenues                          float64
total_revenue_from_operations                     float64
other_income                                      float64
total_income                                      float64
cost_of_materials_consumed                        float64
basis_adjustment_on_hedge_accounted_derivatives   float64
purchase_of_products_for_sale                     float64
changes_in_inventories                            float64
employee_benefits_expense                         float64
finance_costs                                     float64
ccp_share_fair_value_gain_loss                    float64
foreign_exchange_gain_loss_net                    float64
depreciation_and_amortisation_expense             float64
product_development_engineering_expenses          float64
other_expenses                                    float64
amount_transferred_to_capital_and_other_account   float64
total_expenses                                    float64
profit_before_share_exceptional_items_and_tax     float64
share_of_profit_loss_equity_accounted_investees   float64
profit_before_exceptional_items_and_tax           float64
exceptional_items_loss_net                        float64
profit_before_tax                                 float64
current_tax                                       float64
deferred_tax                                      float64
total_tax_expense_credit                          float64
profit_from_continuing_operations                 float64
profit_loss_from_discontinued_operations          float64
profit_for_year                                   float64
profit_attributable_to_shareholders               float64
profit_attributable_to_non_controlling_interests  float64
notes                                              object
financial_year_original                            object

Data types for balance_sheet:

                                                    dtype
financial_year                                     object
fiscal_year_end                                    object
source_report                                      object
unit                                               object
property_plant_and_equipment                      float64
capital_work_in_progress                          float64
right_of_use_assets                               float64
goodwill                                          float64
other_intangible_assets                           float64
intangible_assets_under_development               float64
investment_in_equity_accounted_investees          float64
non_current_investments                           float64
non_current_finance_receivables                   float64
non_current_loans                                 float64
non_current_other_financial_assets                float64
deferred_tax_assets_net                           float64
non_current_tax_assets_net                        float64
other_non_current_assets                          float64
total_non_current_assets                          float64
inventories                                       float64
current_investments                               float64
trade_receivables                                 float64
cash_and_cash_equivalents                         float64
bank_balances_other_than_cash                     float64
current_finance_receivables                       float64
current_loans                                     float64
current_other_financial_assets                    float64
current_tax_assets_net                            float64
other_current_assets                              float64
total_current_assets_excluding_held_for_sale      float64
assets_classified_as_held_for_sale                float64
total_assets                                      float64
equity_share_capital                              float64
other_equity                                      float64
equity_attributable_to_owners                     float64
non_controlling_interests                         float64
total_equity                                      float64
non_current_borrowings                            float64
non_current_lease_liabilities                     float64
ccps_liability_portion                            float64
non_current_other_financial_liabilities           float64
non_current_provisions                            float64
deferred_tax_liabilities_net                      float64
other_non_current_liabilities                     float64
total_non_current_liabilities                     float64
current_borrowings                                float64
current_lease_liabilities                         float64
trade_payables_micro_small_enterprises            float64
trade_payables_others                             float64
acceptances                                       float64
current_other_financial_liabilities               float64
other_current_liabilities                         float64
current_provisions                                float64
current_tax_liabilities_net                       float64
liabilities_associated_with_assets_held_for_sale  float64
total_current_liabilities                         float64
total_equity_and_liabilities                      float64
notes                                              object
financial_year_original                            object

Data types for cash_flow_statement:

                                                  dtype
financial_year                                   object
year_end                                         object
profit_for_year                                 float64
depreciation_and_amortisation                   float64
cash_flow_before_working_capital_changes        float64
cash_generated_from_operations                  float64
income_tax_paid                                 float64
net_cash_from_operating_activities              float64
payments_for_property_plant_equipment           float64
payments_for_intangible_assets                  float64
total_capex_payments                            float64
proceeds_from_sale_of_property_plant_equipment  float64
interest_received                               float64
dividend_received                               float64
net_cash_used_in_investing_activities           float64
proceeds_from_long_term_borrowings              float64
repayment_of_long_term_borrowings               float64
proceeds_from_short_term_borrowings             float64
repayment_of_short_term_borrowings              float64
interest_paid                                   float64
dividend_paid                                   float64
net_cash_from_financing_activities              float64
net_increase_decrease_cash_equivalents          float64
opening_cash_and_cash_equivalents               float64
cash_reclassified_or_disposed                   float64
effect_of_fx_on_cash                            float64
closing_cash_and_cash_equivalents               float64
auto_free_cash_flow                             float64
source_report                                    object
unit                                             object
notes                                            object
financial_year_original                          object

Data types for financial_ratios:

                                         dtype
financial_year                          object
revenue_from_operations_cr             float64
total_income_cr                        float64
profit_before_tax_cr                   float64
profit_after_tax_cr                    float64
total_assets_cr                        float64
total_equity_cr                        float64
total_liabilities_cr                   float64
current_assets_cr                      float64
current_liabilities_cr                 float64
cash_and_cash_equivalents_cr           float64
current_investments_cr                 float64
total_borrowings_cr                    float64
net_cash_from_operating_activities_cr  float64
auto_free_cash_flow_cr                 float64
capex_payments_cr                      float64
net_profit_margin_pct                  float64
pbt_margin_pct                         float64
expense_to_income_ratio_pct            float64
return_on_assets_pct                   float64
return_on_equity_pct                   float64
asset_turnover_ratio                   float64
current_ratio                          float64
quick_ratio                            float64
cash_ratio                             float64
working_capital_cr                     float64
debt_to_equity_ratio                   float64
debt_ratio                             float64
operating_cash_flow_margin_pct         float64
free_cash_flow_margin_pct              float64
capex_to_revenue_pct                   float64
source_income_statement                 object
source_balance_sheet                    object
source_cash_flow                        object
notes                                   object
financial_year_original                 object

## 10. Validate key accounting relationships

I run basic validation checks to catch obvious data issues before moving to deeper analysis. These checks are not a replacement for audit-level verification, but they help me confirm that the extracted datasets behave logically.

In [14]:
validation_results = validation_messages.copy()

def add_check(dataset, check_name, status, details=""):
    validation_results.append({
        "dataset": dataset,
        "check_name": check_name,
        "status": status,
        "details": details,
    })

# I check that total assets match total equity and liabilities where both columns are available.
if {"total_assets", "total_equity_and_liabilities"}.issubset(balance_clean.columns):
    difference = (balance_clean["total_assets"] - balance_clean["total_equity_and_liabilities"]).abs()
    max_difference = difference.max()
    status = "PASS" if max_difference < 1 else "REVIEW"
    add_check(
        "balance_sheet",
        "total_assets_equals_total_equity_and_liabilities",
        status,
        f"maximum absolute difference = {max_difference}",
    )

# I check that revenue is positive for all five years.
revenue_col = "total_revenue_from_operations"
if revenue_col in income_clean.columns:
    positive_revenue = (income_clean[revenue_col] > 0).all()
    add_check(
        "income_statement",
        "positive_revenue_all_years",
        "PASS" if positive_revenue else "FAIL",
        f"minimum revenue = {income_clean[revenue_col].min()}",
    )

# I check that total assets are positive for all five years.
if "total_assets" in balance_clean.columns:
    positive_assets = (balance_clean["total_assets"] > 0).all()
    add_check(
        "balance_sheet",
        "positive_total_assets_all_years",
        "PASS" if positive_assets else "FAIL",
        f"minimum total assets = {balance_clean['total_assets'].min()}",
    )

validation_summary = pd.DataFrame(validation_results)
display(validation_summary)

               dataset                                        check_name status                            details
0     income_statement                          expected_financial_years   PASS       missing=[]; extra=[]; rows=5
1        balance_sheet                          expected_financial_years   PASS       missing=[]; extra=[]; rows=5
2  cash_flow_statement                          expected_financial_years   PASS       missing=[]; extra=[]; rows=5
3     financial_ratios                          expected_financial_years   PASS       missing=[]; extra=[]; rows=5
4        balance_sheet  total_assets_equals_total_equity_and_liabilities   PASS  maximum absolute difference = 0.0
5     income_statement                        positive_revenue_all_years   PASS        minimum revenue = 249794.75
6        balance_sheet                   positive_total_assets_all_years   PASS   minimum total assets = 330619.93

## 11. Merge datasets into one validation table

I merge the income statement, balance sheet, cash flow statement, and financial ratios datasets on the standardized `financial_year` column.

This is the corrected merge step. The final output should have exactly five rows: FY2021 to FY2025.

In [15]:
combined_validation = (
    income_clean
    .merge(balance_clean, on="financial_year", how="outer", suffixes=("_income", "_balance"))
    .merge(cashflow_clean, on="financial_year", how="outer", suffixes=("", "_cashflow"))
    .merge(ratios_clean, on="financial_year", how="outer", suffixes=("", "_ratios"))
)

# I sort the merged dataset in proper financial year order.
combined_validation["financial_year"] = pd.Categorical(
    combined_validation["financial_year"],
    categories=expected_years,
    ordered=True
)
combined_validation = combined_validation.sort_values("financial_year").reset_index(drop=True)
combined_validation["financial_year"] = combined_validation["financial_year"].astype(str)

print("Combined validation dataset shape:", combined_validation.shape)
print("Final financial years:", combined_validation["financial_year"].tolist())
display(combined_validation.head())

Combined validation dataset shape: (5, 160)
Final financial years: ['FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025']

,financial_year,source_report_income,unit_income,revenue,other_operating_revenues,total_revenue_from_operations,other_income,total_income,cost_of_materials_consumed,basis_adjustment_on_hedge_accounted_derivatives,purchase_of_products_for_sale,changes_in_inventories,employee_benefits_expense,finance_costs,ccp_share_fair_value_gain_loss,foreign_exchange_gain_loss_net,depreciation_and_amortisation_expense,product_development_engineering_expenses,other_expenses,amount_transferred_to_capital_and_other_account,total_expenses,profit_before_share_exceptional_items_and_tax,share_of_profit_loss_equity_accounted_investees,profit_before_exceptional_items_and_tax,exceptional_items_loss_net,profit_before_tax,current_tax,deferred_tax,total_tax_expense_credit,profit_from_continuing_operations,profit_loss_from_discontinued_operations,profit_for_year,profit_attributable_to_shareholders,profit_attributable_to_non_controlling_interests,notes_income,financial_year_original_income,fiscal_year_end,source_report_balance,unit_balance,property_plant_and_equipment,capital_work_in_progress,right_of_use_assets,goodwill,other_intangible_assets,intangible_assets_under_development,investment_in_equity_accounted_investees,non_current_investments,non_current_finance_receivables,non_current_loans,non_current_other_financial_assets,deferred_tax_assets_net,non_current_tax_assets_net,other_non_current_assets,total_non_current_assets,inventories,current_investments,trade_receivables,cash_and_cash_equivalents,bank_balances_other_than_cash,current_finance_receivables,current_loans,current_other_financial_assets,current_tax_assets_net,other_current_assets,total_current_assets_excluding_held_for_sale,assets_classified_as_held_for_sale,total_assets,equity_share_capital,other_equity,equity_attributable_to_owners,non_controlling_interests,total_equity,non_current_borrowings,non_current_lease_liabilities,ccps_liability_portion,non_current_other_financial_liabilities,non_current_provisions,deferred_tax_liabilities_net,other_non_current_liabilities,total_non_current_liabilities,current_borrowings,current_lease_liabilities,trade_payables_micro_small_enterprises,trade_payables_others,acceptances,current_other_financial_liabilities,other_current_liabilities,current_provisions,current_tax_liabilities_net,liabilities_associated_with_assets_held_for_sale,total_current_liabilities,total_equity_and_liabilities,notes_balance,financial_year_original_balance,year_end,profit_for_year_cashflow,depreciation_and_amortisation,cash_flow_before_working_capital_changes,cash_generated_from_operations,income_tax_paid,net_cash_from_operating_activities,payments_for_property_plant_equipment,payments_for_intangible_assets,total_capex_payments,proceeds_from_sale_of_property_plant_equipment,interest_received,dividend_received,net_cash_used_in_investing_activities,proceeds_from_long_term_borrowings,repayment_of_long_term_borrowings,proceeds_from_short_term_borrowings,repayment_of_short_term_borrowings,interest_paid,dividend_paid,net_cash_from_financing_activities,net_increase_decrease_cash_equivalents,opening_cash_and_cash_equivalents,cash_reclassified_or_disposed,effect_of_fx_on_cash,closing_cash_and_cash_equivalents,auto_free_cash_flow,source_report,unit,notes,financial_year_original,revenue_from_operations_cr,total_income_cr,profit_before_tax_cr,profit_after_tax_cr,total_assets_cr,total_equity_cr,total_liabilities_cr,current_assets_cr,current_liabilities_cr,cash_and_cash_equivalents_cr,current_investments_cr,total_borrowings_cr,net_cash_from_operating_activities_cr,auto_free_cash_flow_cr,capex_payments_cr,net_profit_margin_pct,pbt_margin_pct,expense_to_income_ratio_pct,return_on_assets_pct,return_on_equity_pct,asset_turnover_ratio,current_ratio,quick_ratio,cash_ratio,working_capital_cr,debt_to_equity_ratio,debt_ratio,operating_cash_flow_margin_pct,free_cash_flow_margin_pct,capex_to_revenue_pct,source_income_statement,source_balance_sheet,source_cash_flow,notes_ratios,financial_year_original_ratios
0,FY2021,tata-motor-IAR-2020-21.pdf,₹ crore,246972.17,2822.58,249794.75,2643.19,252437.94,141357.27,-35.16,12250.09,4684.16,27648.48,8097.17,NaN,-1732.15,23546.71,5226.63,40921.97,-12849.13,249151.20,NaN,-378.96,3286.74,13761.02,-10474.28,1710.18,831.68,2541.86,-13016.14,NaN,-13395.10,-13451.39,56.29,FY21 statement presents share of joint venture...,FY2021,2021-03-31,76th Integrated Annual Report 2020-21,INR crore,79640.05,8377.14,6490.66,803.72,51773.18,12586.79,4200.79,1368.30,16846.82,1204.59,5813.98,4520.35,1003.30,1608.49,196238.16,36088.59,19051.19,12679.08,31700.01,15092.45,17868.09,1749.40,5274.32,865.31,6298.40,146666.84,220.80,343125.80,765.81,54480.91,55246.72,1573.49,56820.21,93112.77,5412.06,NaN,2556.35,13606.76,1555.89,12312.58,128556.41,21662.79,814.00,186.21,67993.63,7860.31,34854.59,10443.18,12848.03,1086.44,0.00,157749.18,343125.80,Consolidated balance sheet; total_current_asse...,FY2020-21,2021-03-31,-13395.10,23546.71,31197.64,31105.07,-2104.56,29000.51,-11775.65,-8429.75,-20205.40,350.58,427.51,18.37,-26126.25,29642.36,-18629.61,20807.15,-11078.93,-8122.94,-1.56,9904.20,12778.46,18467.80,0.0,453.75,31700.01,5317.0,tata-motor-IAR-2021-22.pdf / tata-motor-IAR-20...,INR crore,FY21 cash-flow figures taken from consolidated...,FY2020_21,249794.75,252437.94,-10474.28,-13395.10,343125.80,56820.21,286305.59,146887.64,157749.18,31700.01,19051.19,114775.56,29000.51,5317.0,-20205.40,-5.36,-4.19,98.70,-3.90,-23.57,0.728,0.93,0.70,0.32,-10861.54,2.02,0.83,11.61,2.13,8.09,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...,FY2020-21
1,FY2022,tata-motor-IAR-2021-22.pdf,₹ crore,275235.23,3218.39,278453.62,3053.63,281507.25,160920.56,1322.50,18374.77,1590.49,30808.52,9311.86,14.45,78.68,24835.69,9209.50,47133.85,-14397.29,287881.08,NaN,-74.06,-6373.83,629.58,-7003.41,2669.98,1561.31,4231.29,-11234.70,NaN,-11308.76,-11441.47,132.71,FY22 statement presents share of joint venture...,FY2022,2022-03-31,77th Integrated Annual Report 2021-22,INR crore,80900.13,3529.04,6686.02,807.17,50462.13,6722.05,4349.39,2320.92,11135.85,843.35,5179.49,3870.85,1196.79,5639.21,183642.39,35240.34,22709.22,12442.12,38159.01,2510.18,22095.35,1671.93,3799.82,259.84,7565.88,146453.69,523.85,330619.93,765.88,43795.36,44561.24,4271.06,48832.30,97759.17,5962.44,NaN,5333.66,12955.89,1558.44,7535.22,131104.82,41917.87,809.55,183.92,59786.46,9779.95,14420.24,11761.54,10766.31,1253.85,3.12,150682.81,330619.93,Consolidated balance sheet; assets held-for-sa...,FY2021-22,2022-03-31,-11308.76,24835.69,26942.77,16192.47,-1909.64,14282.83,-9039.40,-6129.02,-15168.42,230.10,652.94,32.01,-4775.12,31308.62,-23355.80,16866.24,-19460.45,-9251.42,-1.53,-3380.17,6127.54,31700.01,0.0,331.46,38159.01,-9254.0,tata-motor-IAR-2022-23.pdf / tata-motor-IAR-20...,INR crore,FY22 values use latest comparative where avail...,FY2021_22,278453.62,281507.25,-7003.41,-11308.76,330619.93,48832.30,281787.63,146977.54,150682.81,38159.01,22709.22,139677.04,14282.83,-9254.0,-15168.42,-4.06,-2.52,102.26,-3.36,-21.41,0.827,0.98,0.74,0.40,-3705.27,2.86,0.85,5.13,-3.32,5.45,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...,FY2021-22
2,FY2023,tata-motor-IAR-2022-23.pdf,₹ crore,342874.59,3092.38,345966.97,4633.18,350600.15,208944.31,726.26,22306.95,-4781.62,33654.70,10225.48,13.75,-103.88,24860.36,10661.96,61785.96,-18434.84,349133.13,NaN,336.38,1467.02,-1590.53,3057.55,3258.35,-2554.29,704.06,2353.49,NaN,2689.87,2414.29,275.58,FY23 statement presents share of joint venture...,FY2023,2023-03-31,78th Integrated Annual Report 2022-23 / 79th I...,INR crore,76641.43,5219.87,7801.04,840.60,46796.69,9054.63,4675.66,2865.19,7416.41,745.31,7153.00,5184.67,1556.36,8602.05,184552.91,40755.39,18838.31,15737.97,31886.95,5128.61,23417.31,123.53,4966.03,259.26,9587.33,150700.69,827.78,336081.38,766.02,44555.77,45321.79,7277.72,52599.51,88695.81,7568.49,2500.0,5822.47,13196.53,1406.95,9264.29,128454.54,36964.66,884.48,316.01,71739.76,7195.99,13828.58,11033.00,11810.66,1254.19,0.00,155027.33,336081.38,Consolidated balance sheet; FY23 values kept i...,FY2022-23,2023-03-31,2689.87,24860.36,41694.13,38567.00,-3178.99,35388.01,-8492.63,-9603.05,-18095.68,285.03,973.44,46.42,-16804.16,16315.06,-31559.46,28125.45,-30997.82,-9335.96,0.00,-26242.90,-7659.05,38159.01,0.0,1386.99,31886.95,7840.0,tata-motor-IAR-2023-24.pdf / tata-motor-IAR-20...,INR crore,FY23 values taken from consolidated cash-flow ...,FY2022_23,345966.97,350600.15,3057.55,2689.87,336081.38,52599.51,283481.87,151528.47,155027.33,31886.95,18838.31,125660.47,35388.01,7840.0,-18095.68,0.78,0.88,99.58,0.81,5.30,1.038,0.98,0.71,0.33,-3498.86,2.39,0.84,10.23,2.27,5.23,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...,FY2022-23
3,FY2024,tata-motor-IAR-2023-24.pdf,₹ crore,434984.12,2943.65,437927.77,5949.92,443877.69,249277.79,NaN,25043.44,-1565.53,42486.64,9985.76,47.90,23.84,27270.13,10958.72,78874.98,-26758.35,415645.32,28232.37,699.80,28932.17,977.06,27955.11,4937.13,-8788.77,-3851.64,NaN,NaN,31806.75,31399.09,407.66,FY24 statement includes share of profit in equ...,FY2024,2024-03-31,79th Integrated Annual Report 2023-24,INR crore,73124.66,10937.33,8059.49,860.26,39241.05,24761.10,5340.28,3377.55,6094.66,441.58,9084.66,13099.02,2129.73,5720.44,202271.81,47788.29,14253.24,16951.81,40014.76,5791.93,24069.50,196.70,8121.47,101.15,10429.39,167718.24,673.91,370663.96,766.50,84151.52,84918.02,8175.91,93093.93,62148.53,7669.52,2547.9,1673.12,16536.66,1143.35,12233.95,103953.03,36351.56,1092.89,502.31,87540.64,5935.57,15385.12,12990.30,12291.47,1527.14,0.00,173617.00,370663.96,Consolidated balance sheet.,FY2023-24,2024-03-31,31806.75,27270.13,65106.46,72431.63,-4516.27,67915.36,-12974.74,-18438.89,-31413.63,231.09,2492.74,46.70,-22828.09,11629.40,-31675.20,10194.10,-15656.51,-9332.32,-769.27,-37005.99,8081.28,31886.95,0.0,46.53,40014.76,26924.0,tata-motor-IAR-2024-25.pdf / tata-motor-IAR-20...,INR crore,FY24 cash-flow values include latest re-presen...,FY2023_24,437927.77,443877.69,27955.11,31806.75,370663.96,93093.93,277570.03,168392.15,173617.00,40014.76,14253.24,98500.09,67915.36,26924.0,-31413.63,7.26,6.38,93.64,9.00,43.66,1.239,0.97,0.69,0.31,-5224.85,1.06,0.75,15.51,6.15,7.17,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...,FY2023-24
4,FY2025,tata-motor-IAR-2024-25.pdf,₹ crore,436821.00,2874.00,439695.00,6244.00,445939.00,241148.00,NaN,27802.00,2836.00,47767.00,5083.00,-84.00,-922.00,23256.00,10716.00,85399.00,-31105.00,411896.00,34043.00,287.00,34330.00,550.00,33780.00,5023.00,5479.00,10502.00,23278.00,4871.0,28149.00,27830.00,319.00,FY25 values are rounded to whole crores as pre...,FY2025,2025-03-31,80th Integrated Annual Report 2024-25,INR crore,72536.00,17624.00,8476.00,895.00,33790.00,48182.00,5534.00,2923.00,0.00,99.00,12185.00,7176.00,2045.00,6852.00,218317.00,47269.00,27199.00,13248.00,34349.00,6485.00,0.00,72.00,18984.00,411.00,11794.00,159811.00,514.00,378642.00,736.00,115408.00,116144.00,6610.00,122754.00,40217.00,7642.00,2464.0,901.00,20935.00,1669.00,15376.00,89204.00,22282.00,1399.00,452.00,93626.00,3290.00,14318.00,13340.00,15831.00,2146.00,0.00,166684.00,378642.00,Consolidated balance sheet; FY25 report presen...,FY2024-25,2025-03-31,28149.00,23256.00,58937.00,67093.00,-3991.00,63102.00,-15189.00,-22853.00,-38042.00,974.00,2420.00,64.00,-47594.00,7386.00,-19600.00,846.00,-1843.00,-5814.00,-2303.00,-18786.00,-3278.00,40015.00,-3231.0,843.00,34349.00,22348.0,tata-motor-IAR-2024-25.pdf,INR crore,FY25 consolidated cash-flow statement; cash_re...,FY2024_25,439695.00,445939.00,33780.00,28149.00,378642.00,122754.00,255888.00,160325.00,166684.00,34349.00,27199.00,62499.00,63102.00,22348.0,-38042.00,6.40,7.68,92.37,7.51,26.08,1.174,0.96,0.68,0.37,-6359.00,0.51,0.68,14.35,5.08,8.65,income_statement_combined_FY2021_to_FY2025.csv,balance_sheet_combined_FY2021_to_FY2025.csv,cash_flow_statement_combined_FY2021_to_FY2025.csv,ROA/ROE/asset turnover use average assets/equi...,FY2024-25

## 12. Final merge quality check

Before exporting, I confirm that the merged dataset has only the five expected years. This prevents me from saving a wrong output with duplicate year formats like `FY2020-21`, `FY2020_21`, and `FY2021` as separate rows.

In [16]:
final_years = combined_validation["financial_year"].tolist()

if final_years != expected_years:
    raise ValueError(
        f"The merged dataset has incorrect financial years: {final_years}. Expected: {expected_years}"
    )

if combined_validation.shape[0] != 5:
    raise ValueError(
        f"The merged dataset should have exactly 5 rows, but it has {combined_validation.shape[0]} rows."
    )

print("Final merge check passed.")
print("The dataset now has one clean row for each year from FY2021 to FY2025.")

Final merge check passed.
The dataset now has one clean row for each year from FY2021 to FY2025.

## 13. Export validated outputs

I export the final validation dataset and the validation summary so that I can use them in the next analysis notebooks, Excel, SQL, Power BI, and the final report.

In [17]:
output_validation_path = DATA_CLEANED / "validated_financial_dataset.csv"
output_report_path = REPORTS_DIR / "data_validation_summary.csv"

combined_validation.to_csv(output_validation_path, index=False)
validation_summary.to_csv(output_report_path, index=False)

print("Validated financial dataset exported to:", output_validation_path)
print("Data validation summary exported to:", output_report_path)

Validated financial dataset exported to: d:\Github Project\Tata Motors Financial Analysis\data\cleaned\validated_financial_dataset.csv
Data validation summary exported to: d:\Github Project\Tata Motors Financial Analysis\reports\data_validation_summary.csv

## 14. Initial observations for the next notebook

After completing this validation step, my datasets are ready for deeper financial analysis.

In the next notebook, I will analyze:

- revenue and profit trends
- profitability margins
- liquidity ratios
- debt and solvency position
- cash flow strength
- business health indicators

This validated dataset will help me build the analysis without carrying forward year-format errors.